#!/bin/sh /etc/rc.common
# (C) 2013 openwrt.org
# (C) 2016 Hendrik Linka (Fraunhofer Gesellschaft)

START=13

start() {
	echo "this file has been obsoleted. please call \"/sbin/block mount\" directly"
	/sbin/block mount
	/bin/usb_sync &
	#Check if config exists
	if [ -d "/mnt/sda1/config" ]; then
		echo Config exists > /dev/kmsg
		# Copy only files that are bigger than zero.
		find /mnt/sda1/config/* -size +1c -exec cp -r {} /etc/config \;
		
	fi
	echo `ls /mnt/sda1` > /dev/kmsg
}

stop() {
	echo "this file has been obsoleted. please call \"/sbin/block umount\" directly"
	/sbin/block umount
}
